name: Build And Publish

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow is made up of one or more jobs that can run sequentially or in
# parallel
jobs:

  # Job for building the LateX files
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of
    # the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      - name: Checkout source code
        uses: actions/checkout@v3

      # Build the LaTeX document to create a PDF file
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curriculum_vitae.tex

      # Prepare the Github Pages content
      - name: Prepare Github page
        run: mv curriculum_vitae.pdf website/Diego_Smania_CV_English.pdf

      # Package and upload an artifact for deployment into Github Pages.
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: website

  # Deploy to Github pages
  deploy:

    # This job requires the build job to be executed first
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Deploy to Github pages
      # TODO: Review this step...
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact-name: build
